name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install and build shared package
        run: npm install && npm run build
        working-directory: packages/shared
      - name: Install dependencies
        run: npm install
        working-directory: apps/api
      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: apps/api
      - name: Build
        run: npm run build
        working-directory: apps/api

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
        working-directory: apps/web
      - name: Build
        run: npm run build
        working-directory: apps/web
